### ISSUE TITLE
Add auto completion in colcon_cd

### ISSUE THREAD

**Issue by vincentrou** [colcon/colcon-cd#12]
Auto complete package name from colcon list output

**Comment by dirk-thomas** [comment]
Completion would be a nice feature. Please consider to contribute a pull request.

**Comment by legendPerceptor** [comment]
After installing the colon package, you can just source the `argcomplete` bash file, which is located in `/usr/share/colcon_argcomplete/hook/colcon-argcomplete.bash`.

**Comment by Briancbn** [comment]
@dirk-thomas I played around with this a bit and managed to get a working prototype in the PR.

**Comment by dirk-thomas** [comment]
@Briancbn Sorry, I am not the maintainer of this repository anymore.

**Comment by Briancbn** [comment]
Pinging again here.

**Comment by imartinez-swri** [comment]
I might be missing the point here but why not just add something like this to your bash.


```shell
export COLCON_LOG_PATH=<your-log-path>


_colcon_cd_complete() {

    local current_word
    current_word="${COMP_WORDS[COMP_CWORD]}"

    # Get the list of package names using colcon list
    local packages
    packages=$(colcon list --base-paths [PATH ...] 2>/dev/null)

    # Filter the package names based on the current word being completed
    COMPREPLY=($(compgen -W "$packages" -- "$current_word"))
}

# Register completion for colcon_cd
complete -F _colcon_cd_complete colcon_cd
```
